dotnet EOL warning suppression
svenheden/csharp-models-to-typescript pull request #70
Opened 2023-05-17 11:56 UTC by CharlieSaunders

Adding a property to the dotnet run process that will suppress EOL Framework warnings based on the bool from the config.

When using the package on older frameworks, the dotnet run process; rightly, displays that the framework being used has reached EOL. This however means that the JSON generated is invalid as it contains warnings IE:

C:\dotnet\sdk\7.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\path\to\the\node_modules\csharp-models-to-typescript\lib\csharp-models-to-json\csharp-models-to-json.csproj]
[{foo:bar}]

Which when ran through JSON.parse; index.js: 70, errors with "Unexpected token C in JSON at position 0". 

Adding this additional parameter on the config; suppressEolFrameworkErrors, suppresses those EOL warnings and only the generated JSON is sent for parsing.

2024-05-23 20:37 UTC, digocesar requested changes
Please rebase this branch to the current `master` that has automated tests.

2024-05-23 20:37 UTC, digocesar commented on index.js
> +const dotnetProcess = spawn('dotnet', processParameters, { shell: true });
Hi @CharlieSaunders .
The variable `processParameters` is erronealy typed before as processParam**a**ters. Can you fix it?

2024-05-23 20:37 UTC, digocesar commented on index.js
> +if(config.suppressEolFrameworkErrors){
May be put space caracter after the `if` and before `{` to be bether formmated. 😉

2024-05-23 20:49 UTC, digocesar commented
@svenheden and/or @SafeerH.
If dotnet process has this option to ignore EOL error, is not better to always pass this parameter to do not emmit the EOL error?
We had updated `main` to .Net 8.0, but this parameter can avoid the component stops working in the future, as happened recently.

2024-05-23 20:54 UTC, svenheden commented
> If dotnet process has this option to ignore EOL error, is not better to always pass this parameter to do not emmit the EOL error?

Yes that sounds like a good idea. I can't think of a scenario where you'd want to show that EOL error causing the JSON to be corrupted.

2024-05-23 21:11 UTC, SafeerH commented
The root cause for the problem is the way of extracting the JSON from the console output.
If there's anything else apart from the JSON string in the Console output (stdout), the program breaks. Also relates to #61 
So, I think we need to find a broader solution that will isolate the JSON irrespective of other console outputs. 
I'm thinking of printing the JSON between markers, that will help us isolate the JSON.
I will try this approach and let you guys know. Thanks!

2024-05-24 11:54 UTC, digocesar approved these changes

2024-05-24 11:56 UTC, digocesar commented
Hi @CharlieSaunders. Thanks for your help.
This PR is not needed anymore as the #78 solved the problem.

2024-05-24 11:56 UTC, closed without merging